import "./globals.css";
import Navbar from "@/componrnts/Navbar";
import localFont from 'next/font/local'
 
const myFont = localFont({
  src: './font/Outfit-Regular.ttf',
})
 
export const metadata = {
  title: "Compress your Links",
  description: "Generated by Harsh upla",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className}`}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}